### ISSUE TITLE
cluster-autoscaler should implement create_namespace in helm resource

### ISSUE THREAD

**Issue by qvistgaard** [nuuday/terraform-aws-eks-addons#11]
if implemted we can make namespace configurable using variables and then we don't have to deal with the namespace resource

**Comment by anarsen** [comment]
If you'll adopt the same approach in the Prometheus, Loki, and Cilium add-ons we're good to go.

**Comment by qvistgaard** [comment]
Just added it to #6

**Comment by anarsen** [comment]
Closing this as it's made irrelevant by #16 and friends.
