### ISSUE TITLE
What should our wrapper module look like

### ISSUE THREAD

**Issue by wolffberg** [nuuday/terraform-aws-eks-addons#15]
We should decide on the way we want to implement our wrapper module. A few examples could be:

1. Enable modules using a bool from the wrapper module, only initializing the module block when True.
2. Pass through a bool variable to every addon module and let the module decide how it handles the input.

I vote for option 1 but as it will only be available from Terraform 0.13+ and that version is currently in beta, we might run with version 2 until then. I still think we should decide on the final implementation though.

**Comment by anarsen** [comment]
Could you add a few examples demonstrating points 1 and 2?

I assume 1) is related to the `count` support on `module` blocks in Terraform 0.13+, but not sure what you mean in 2).

**Comment by wolffberg** [comment]
I've encountered a few more issues we need to think about. This is an example from the OP.

**Option 1**

_main.tf_
```
module "cluster-autoscaler" {
  count  = var.cluster_autoscaler_enable ? 1 : 0

  var1 = var.cluster_autoscaler_var1
  var2 = var.cluster_autoscaler_var2
  ...
}
```

**Option 2**

_main.tf_
```
module "cluster-autoscaler" {
  enable = var.cluster_autoscaler_enable
  var1 = var.cluster_autoscaler_var1
  var2 = var.cluster_autoscaler_var2
  ...
}
```

We also need to take into account how we pass on variables to the addons. My current suggestion would be to find a way to reflect the addon Terraform files, pull variables and prepend the name of the addon (eg. _worker_count_ in an addon would become _addon_worker_count_ in the wrapper). This would prevent clashes of variable names between addons.

**Comment by anarsen** [comment]
Another suggestion for passing addon-specific variables from the root module

```terraform
# my-main.tf

module "addons" {
  source = "github.com/nuuday/terraform-aws-eks-addons"

  cluster_autoscaler = {
    enable = true
  }

  external_dns = {
    enable = true
    dns_validation = true
    zone_ids = [
      # xyz,
    ]
  }
}
```

These structures can be validated through the `variable` block

```terraform
# variables.tf

variable "external_dns" {
  type = object({
    enable = boolean
    zone_ids = list(string)
  })

  default = {
    enable = false
    zone_ids = []
  }
}
```

**Comment by anarsen** [comment]
#7 is related in how we want to define resource requests.

**Comment by wolffberg** [comment]
`main.tf`, `variables.tf` and `outputs.tf` has been added to the [main-module branch](https://github.com/nuuday/terraform-aws-eks-addons/tree/main-module). When using [this method](https://github.com/nuuday/terraform-aws-eks-addons/issues/15#issuecomment-640407838) to define variables, you can either choose to add all or no variables with defaults. As we need `enabled = false` for all addons I have added all variables with defaults in this first draft.

See [this issue](https://github.com/hashicorp/terraform/issues/19898) describing the problem.

Please take a look at the files and let me know what you think and if you can come up with a better way to do it.

**Comment by anarsen** [comment]
I think it's a very good starting point. I vote for this approach!

One thing: We discussed how we'd define resource requests in variables here #7. Perhaps that could be included here https://github.com/nuuday/terraform-aws-eks-addons/blob/6ee583ec02ab9a71bcd9676743368e56b6909726/variables.tf#L158

**Comment by wolffberg** [comment]
@anarsen @qvistgaard 
Should we scrap the main module all together or keep it in mind when we develop the repo?

**Comment by anarsen** [comment]
I've used the individual modules up until now, and it seemed pretty low-friction to me.

I vote we scrap the main module.

**Comment by qvistgaard** [comment]
I agree, we should scrap the wrapper module

**Comment by anarsen** [comment]
I think we all agree. Closing.
