### ISSUE TITLE
Add-on: CloudWatch Agent for Container Insights

### ISSUE THREAD

**Issue by anarsen** [nuuday/terraform-aws-eks-addons#5]
AWS provides the CloudWatch Agent which sends off metrics and logs from worker nodes and pods to CloudWatch. This solution is called [Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html).

**NOTE** There is a beta version of the CloudWatch Agent capable of scraping Prometheus metrics from pods and putting them into CloudWatch Metrics. Let's try that: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-Prometheus.html

**Comment by anarsen** [comment]
@qvistgaard You may be interested in this one: the CloudWatch Agent now supports scraping of Prometheus metrics, and will export them to CloudWatch Metrics :tada: 

That's at least something I think we'll be using instead of running our own Prometheus.

**Comment by qvistgaard** [comment]
It sounds really nice, i would jump on that as well, however there is a aspect i'm not sure if it have been covered. Today, i can just go to grafana's website and find premade dashboards for the most popular software. i'm not sure this would be possible to do without the prometheus server`?

**Comment by anarsen** [comment]
I know Grafana can visualize metrics from AWS CloudWatch, but I'm not sure if the premade dashboards are tied to the Prometheus data source or not.

If you come across any detail on this, feel free to share it here.

**Comment by qvistgaard** [comment]
I know that each premade dashboard is for a specific datasource. each chart contains datasource specific queries

**Comment by qvistgaard** [comment]
I would like to add another thing which i think you should consider: since prometheus basically the defacto standard for monitoring kubernetes, i think the amount of work that will have to be put into figuring out what to monitor, when to send alarms etc. compared to prometheus because, a lot of community work has already been done towards those goals. take this project for example:

https://github.com/kubernetes-monitoring/kubernetes-mixin

**Comment by anarsen** [comment]
The coming CloudWatch Agent supports scraping Prometheus metrics too, which is what this issue is supposed to track. It's not a discussion on whether or not Prometheus is relevant, because we share your POV - it's the de-facto for scraping and querying metrics in K8s.

Personally, I'd much rather start looking into [OpenTelemetry](https://opentelemetry.io/) tbh. It supports Prometheus as a target too. That's for a separate issue though :slightly_smiling_face:

**Comment by anarsen** [comment]
Feel free to re-open this if you want. I'll close it since I'll not be working directly with EKS or K8s in the Cloud Hosting Services squad :+1:
