### ISSUE TITLE
Uniform way of declaring resource requests

### ISSUE THREAD

**Issue by anarsen** [nuuday/terraform-aws-eks-addons#7]
Instead of having two variables for accepting resource requests for pods, perhaps we could come up with another way.

Instead of
```terraform
variable "resource_requests_cpu" {
  type = number
}

variable "resource_requests_memory" {
  type = number
}
```

then something like
```terraform
variable "resource_requests" {
  type = map(number)
  default = {
    cpu = 100
    memory = 100
  }
}
```

**Comment by qvistgaard** [comment]
I think it is a great idea.

**Comment by anarsen** [comment]
We can actually go a bit further with the type annotation and validate the object keys too

```terraform
variable "resource_requests" {
  type = object({
    cpu    = number
    memory = number
  })  

  default = { 
    cpu    = 100 
    memory = 100 
  }
}
```

cc @wolffberg

**Comment by qvistgaard** [comment]
How would you suggest we define limits, cpu should be optional and omittet if not set

**Comment by anarsen** [comment]
IMO our add-ons must define, although low, **default** resource requests. Otherwise they'll get their QoS classified as _best effort_, which we probably don't want for components we consider "must-haves".

**Comment by qvistgaard** [comment]
I agree, requests must always be set, however in some cases it could make sense not to set cpu limit.
